---
- name: Configure DHCP Server on Ubuntu
  hosts: dhcp
  become: yes

  tasks:

    - name: Install DHCP server package
      apt:
        name: isc-dhcp-server
        state: present
        update_cache: yes

    - name: Configure DHCP server file 
      copy:
        dest: /etc/dhcp/dhcpd.conf
        content: |
          default-lease-time 600;
          max-lease-time 7200;
          authoritative;

          subnet 10.0.2.0 netmask 255.255.255.0 {
            range 10.0.2.50 10.0.2.150;
            option routers 10.0.2.1;
            option subnet-mask 255.255.255.0;
            option domain-name-servers 8.8.8.8, 1.1.1.1;
          }

    - name: Ensure DHCP listens on eth0
      lineinfile:
        path: /etc/default/isc-dhcp-server
        regexp: '^INTERFACESv4='
        line: 'INTERFACESv4="eth0"'

    - name: Enable and restart DHCP service
      systemd:
        name: isc-dhcp-server
        enabled: yes
        state: restarted
